# Generated by Django 4.2.16 on 2025-04-06 14:48

# Generated by Django 4.2.16 on 2025-04-06 14:48

from django.db import migrations
from django.contrib.auth.models import Group, Permission


def create_groups(apps, schema_editor):
    # Create Manager group if it doesn't exist
    manager_group, created = Group.objects.get_or_create(name='Manager')
    
    # Create IC group if it doesn't exist
    ic_group, created = Group.objects.get_or_create(name='IC')


def remove_groups(apps, schema_editor):
    # Remove groups on migration rollback
    Group = apps.get_model('auth', 'Group')
    for group_name in ['Manager', 'IC']:
        try:
            group = Group.objects.get(name=group_name)
            group.delete()
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
