# Generated by Django 4.2.16 on 2025-04-06 17:43

import cloudinary_storage.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=users.models.user_directory_path),
        ),
    ]
