# Generated by Django 4.2.16 on 2025-04-11 10:52

import cloudinary_storage.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_uej1cv.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=users.models.user_directory_path),
        ),
    ]
