# Generated by Django 4.2.16 on 2025-03-18 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(blank=True, related_name='project_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
